apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: cip-source
    deployment: {{VERSION}}
  name: cip-source
  namespace: staging

spec:
  selector:
    matchLabels:
      app: cip-source
  template:
    metadata:
      labels:
        app: cip-source
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
                - spot
      containers:
      - env:
        - name: VERSION
          value: {{VERSION}}
        image: registry.kubernetes.infra.optimy.net/cip/cip-source:{{VERSION}}
        imagePullPolicy: IfNotPresent
        name: copy-source
        volumeMounts:
        - mountPath: /optimy
          name: source
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - hostPath:
          path: /cip-sources
          type: ""
        name: source
