apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ci-cronjob-api-cli
spec:
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: registry.kubernetes.infra.optimy.net/ci/api-cli:{{API_VERSION}}
            imagePullPolicy: IfNotPresent
            name: api-cli 
            volumeMounts:
            - mountPath: /optimy/.env
              name: ci-config
              subPath: .env
          restartPolicy: OnFailure
          volumes:
          - configMap:
              defaultMode: 420
              name: ci-api-config
            name: ci-config
  schedule: "* * * * *"
