apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ci-api-deployment
  labels:
    app: ci-api
    deployment: {{DEPLOYMENT}}
spec:
  replicas: {{CI_API_REPLICA_COUNT}}
  selector:
    matchLabels:
      app: ci-api
  template:
    metadata:
      labels:
        app: ci-api
        deployment: {{DEPLOYMENT}}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
                - spot
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ci-api
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 10
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ci-api
              topologyKey: kubernetes.io/hostname
            weight: 20
      containers:
      - image: lusotycoon/apache-exporter
        imagePullPolicy: Always
        name: exporter
        ports:
        - containerPort: 9117
          protocol: TCP
        resources:
          requests:
            cpu: 10m
      - name: ci-api
        image: registry.kubernetes.infra.optimy.net/ci/api:{{API_VERSION}}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 40m
            memory: 128Mi
          # limits:
          #   cpu: 120m
          #   memory: 384Mi
        # readinessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /optimy/sync.ok
        volumeMounts:
        - mountPath: /optimy/.env
          name: ci-config
          subPath: .env
        ports:
        - containerPort: 80
      volumes:
      - configMap:
          defaultMode: 420
          name: ci-api-config
        name: ci-config

---
kind: Service
apiVersion: v1
metadata:
  name: ci-api-service
  labels:
    app: ci-api
spec:
  selector:
    app: ci-api
  ports:
    - protocol: TCP
      port: 80
      name: ci-api-service
    - protocol: TCP
      port: 9117
      name: exporter
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ci-api-ingress
spec:
  rules:
  - host: api.ci.prod.optimy.net
    http:
      paths:
      - backend:
          serviceName: ci-api-service
          servicePort: 80
status:
  loadBalancer: {}
