apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cip-api-deployment
  labels:
    app: cip-api
    deployment: {{DEPLOYMENT}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cip-api
  template:
    metadata:
      labels:
        app: cip-api
        deployment: {{DEPLOYMENT}}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
                - spot
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cip-api
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 10
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cip-api
              topologyKey: kubernetes.io/hostname
            weight: 20
      containers:
      - image: lusotycoon/apache-exporter
        imagePullPolicy: Always
        name: exporter
        ports:
        - containerPort: 9117
          protocol: TCP
        resources:
          requests:
            cpu: 10m

      - image: registry.kubernetes.infra.optimy.net/cip/cip-source:{{GO_PIPELINE_LABEL}}
        name: cip-api 
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 40m
            memory: 128Mi
        volumeMounts:
        - mountPath: /optimy/api/.env
          name: cip-api-config
          subPath: .env
        - mountPath: /etc/apache2/sites-enabled/000-default.conf
          name: cip-api-apache-config
          subPath: 000-default.conf
        ports:
        - containerPort: 80

      volumes:
      - configMap:
          defaultMode: 420
          name: cip-api-config
        name: cip-api-config
      - configMap:
          defaultMode: 420
          name: cip-api-apache-config
        name: cip-api-apache-config
            

---
kind: Service
apiVersion: v1
metadata:
  namespace: staging
  name: cip-api-service
  labels:
    app: cip-api
spec:
  selector:
    app: cip-api
  ports:
    - protocol: TCP
      port: 80
      name: cip-api-service
    - protocol: TCP
      port: 9117
      name: exporter
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cip-api-ingress
  namespace: staging
spec:
  rules:
  - host: api.cip.staging.optimy.net
    http:
      paths:
      - backend:
          serviceName: cip-api-service
          servicePort: 80
status:
  loadBalancer: {}
