export default Object.freeze({
    YOUTUBE_VIDEO_FORMAT: 'mp4',
    MISSION_TYPE_TIME: 'TIME',
    MISSION_GRID_VIEW_SHORT_DESCRIPTION_CHARACTER : 98,
    MISSION_LIST_VIEW_SHORT_DESCRIPTION_CHARACTER : 150,
    PASSWORD_MIN_LENGTH : 8
})